PACKAGE_NAME="hid-nintendo2"
PACKAGE_VERSION="0.1.0"

MAKE[0]="make KVERSION=${kernelver}"
CLEAN="make clean"

BUILT_MODULE_NAME[0]="hid-nintendo2"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid"

AUTOINSTALL="yes"
